### ISSUE TITLE
Blob URL for definitions file is not publicly accessible

### ISSUE THREAD

**Issue by junecastillote** [microsoft/Get-ExchangeBuildNumber#8]
The URL https://exchangebuildnumbersa.blob.core.windows.net/exchangebuildnumberblob/ExchangeBuildNumbers.csv is not publicly accessible. As a result, the function `Update-ExchangeBuildNumberDefinition` fails with error message `Public access is not permitted on this storage account`.

**Comment by rykoma** [comment]
@junecastillote Thank you for your information. We've enabled anonymous access to the CSV file, so you should now be able to execute `Update-ExchangeBuildNumberDefinition`. Because this is a temporary solution, we'll continue to explore a permanent fix.
